# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Bio
    url: bio/
    weight: 20
  - name: Projects
    weight: 30
    hasChildren: true
  - parent: Projects
    name: Music LM
    url: music-lm/
    weight: 40
  - parent: Projects
    name: Can LLMs solve Wordle?
    url: wordle
    weight: 50

