# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Projects
    weight: 20
    hasChildren: true
  - parent: Projects
    name: Music ML
    url: music_ml/

